### ISSUE TITLE
선택 삭제 문제점.

### ISSUE THREAD

**Issue by bjrambo** [eondcom/xe-package-socialxe#1]
선택 삭제 이나 삭제 버튼에 오류가 있음
이걸 지우는 DB족 연계를 해서 찾아볼 필요가 있을듯..

**Comment by bjrambo** [comment]
@eondcom 포크 해드릴께요. 브랜치 나눠주세요.

**Comment by eondcom** [comment]
반영했습니다. 다음부터는 풀리퀘스트해주시면 바로 반영해놓겠습니다. ^^

**Comment by bjrambo** [comment]
브랜치 따로 나눠서 풀리퀘 받으시는게 좋을것 같아서요.

개발브랜치는 develop 에서 진행하시고 master는 배포 용으로만 marged받아서 운영하는 편이 낫기 때문이지요.

**Comment by bjrambo** [comment]
그리고..클라이언트.html 부분 정확하게 수정이 덜되었네요. 수정을 아에 안건드신것 같습니다.

**Comment by eondcom** [comment]
아! 그 말씀이셨군요^^; 배포본과 개발본을 따로 관리하지 않고 사용했는데
이번엔 말씀대로 그렇게 해봐야겠네요 말씀 감사합니다. ^^

**Comment by eondcom** [comment]
혹시 master에 싱크하면 develo은 따로 싱크하지 않아도 자동으로 싱크가 맞춰지나요? ^^;
제가 사용법이 아직 익숙하지 않아서 미흡한 부분은 도움 말씀 부탁드리겠습니다.^^;

**Comment by bjrambo** [comment]
@eondcom 음 보통은 마스터는 배포일때만 사용하고
develop 에서 모든 개발 업무를 진행 해야합니다.

그리고 develop에서 모든 개발 업무가 마무리 되어 배포할때 됬을 떼 그때 master브랜치로 코드 보내게 됩니다.

제가 develop브랜치를 만들어진 모듈이나 깃허브상에서만 포크하여 코드를 실제로 PR을 남기게 되는데 이유는 마스터상의 코드를 수정하여 다른 사람들이 마스터 항목을 받아 설치시 오류가 있으면 사용에 지장을 주기에 어떤 오류가 있는지 없는지 정확하게 확인하고 그 이후 비로서 배포 했으면 하는게 제 바램이기 때문입니다.

**Comment by bjrambo** [comment]
뭐 이온디님이 진행에 차질이 없으시다면 혹시 이 개발의 대한 부분을 같이 진행 해도 될련지요?

**Comment by eondcom** [comment]
아유 저야 도와주시면 감사하죠 ^^
소셜XE 모듈이 정리되면 플래닛 모듈에도 소셜XE 붙이는 작업 도와주실 수 있나요? ^^;

**Comment by bjrambo** [comment]
@eondcom 어떤작업인지는 모르겠는뎅.. 뭐 암튼.. 소셜XE프로잭트 같이 진행 하고 싶어요 :)

**Comment by eondcom** [comment]
@qw5414 네, 같은 SocialXE 프로젝트라고 보시면 됩니다! ㅎㅎㅎ

**Comment by bjrambo** [comment]
@eondcom 권한이없어요 프로잭트를 옮기던지 이계정에 여기에대한권한이 필요해요

**Comment by eondcom** [comment]
@qw5414 Collaborators 에 람보님 등록했습니다. 이제 권한 있으시죠?

**Comment by bjrambo** [comment]
@eondcom 네 그런듯,. :)
