### ISSUE TITLE
글쓰기시 구글 버튼 이미지 누락

### ISSUE THREAD

**Issue by ppleo** [eondcom/xe-package-socialxe#2]
img width="24" height="24" src="/widgets/socialxe_info/skins/default/images/google_on.png" title="구글 Logout" alt="구글 Logout" class="iePngFix"

위젯의 디폴트에 구글 on/off 이미지가 누락되여 나오지 않습니다. ^^

작은 이미지도 누락되었군요..^^

**Comment by eondcom** [comment]
위젯을 새로 다운받으셨는데 그런가요?

**Comment by ppleo** [comment]
github에 있는것을 다운받았습니다.

**Comment by eondcom** [comment]
게시판은 어떤 걸 사용하세요? 저는 스케치북 게시판 사용하는데
제 환경은 이렇습니다.
http://eond.com/notice/351640#comment_351676
혹시 볼 수 있는 게시판 주소를 알려주실 수 있나요?

**Comment by ppleo** [comment]
저도 스케치북 최신버전입니다.

댓글이 아닌 글쓰기일때입니다.
/widgets/socialxe_info/skins/default/images 소셜 인포 위젯에  빠져 있습니다.

**Comment by eondcom** [comment]
네 확인했습니다. 수정해볼게요~ ^^

**Comment by eondcom** [comment]
수정했습니다. 글쓰기 화면에서 다른 소셜 서비스로 등록이 되나요? 저는 댓글만 되던데-_-?;;

**Comment by ppleo** [comment]
ㅡㅡ;;  페이스북으로 테스트 중인데 전 댓글도 에러가.뜨네요. 본문도 등록이 안돼는군요
되는것은 로그인만..ㅡㅡ;;헐

아 그리고 구글 버튼은 작은 이미지도 있어야 합니다. ^^

![untitled-1](https://cloud.githubusercontent.com/assets/5974818/5274582/2298ab72-7ada-11e4-9ccc-25cc8f058280.jpg)

**Comment by eondcom** [comment]
socialXE server를 자기 계정에 업로드해서 사용하실 경우 페이스북은 리뷰를 작성하고 통과해야 오류가 나타나지 않습니다.

**Comment by ppleo** [comment]
엡 ^^ 검색을 해보니 나오는군요 ..리뷰를...으윽...절차가 복잡하기는 하네요..ㅋㅋ

**Comment by eondcom** [comment]
저도 해봤는데 엄청 복잡했습니다. 제대로 됐는지 모르겠네요. 아직 페이스북에 글 등록이 안되서.. 오류는 안 나타나는 것 같기는 합니다만.
